# Generated by Django 6.0.6 on 2026-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knihy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('rok_vydani', models.IntegerField()),
                ('dostupna', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knihy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzivatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('heslo', models.CharField(max_length=255)),
                ('datum_registrace', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uzivatele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vypujcky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vypujceni', models.DateTimeField(blank=True, null=True)),
                ('datum_vraceni', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vypujcky',
                'managed': False,
            },
        ),
    ]
